const ANIMATION_SLIDE_DURATION = 400;  // ms
const ANIMATION_SPAWN_DURATION = 400;
const ARROW_PRESS_TIMEOUT = ANIMATION_SLIDE_DURATION;
const MOCK_SCENARIO = 'almostWon';  // {"noMock"|"almostLost"|"almostWon"|"oneMissing"}
const ANIMATION_NEEDED = true;



module.exports = {
  ARROW_PRESS_TIMEOUT,
  ANIMATION_SLIDE_DURATION,
  MOCK_SCENARIO,
  ANIMATION_NEEDED,
  ANIMATION_SPAWN_DURATION,
};
